from codenames.boards import build_board
from codenames.game import Board, Card, CardColor

HEBREW_WORDS = [
    "מטען",
    "עלילה",
    "ניצחון",
    "כבש",
    "יוגה",
    "צבי",
    "אף",
    "מפגש",
    "דק",
    "פרץ",
    "שלם",
    "אדם",
    "הרמוניה",
    "זכוכית",
    "חשמל",
    "מעטפת",
    "אנרגיה",
    "קברן",
    "נחת",
    "חייזר",
    "שיר",
    "מיליונר",
    "לפיד",
    "יקום",
    "דרור",
]

HEBREW_BOARD_1 = build_board(vocabulary=HEBREW_WORDS, seed=1)
HEBREW_BOARD_2 = build_board(vocabulary=HEBREW_WORDS, seed=2)
HEBREW_BOARD_3 = build_board(vocabulary=HEBREW_WORDS, seed=3)

# Regex: 'Parsed card: (.*) (.*)' -> 'Card(word="$2", color=CardColor.$1),'

HEBREW_BOARD_DIFFICULT = Board(
    cards=[
        Card(word="בריטניה", color=CardColor.GRAY),
        Card(word="מרכז", color=CardColor.BLUE),
        Card(word="נבחר", color=CardColor.GRAY),
        Card(word="שניה", color=CardColor.GRAY),
        Card(word="טרמפ", color=CardColor.RED),
        Card(word="ברברי", color=CardColor.BLUE),
        Card(word="נשק", color=CardColor.BLUE),
        Card(word="תוכן", color=CardColor.RED),
        Card(word="קיסריה", color=CardColor.GRAY),
        Card(word="גלידה", color=CardColor.RED),
        Card(word="ארז", color=CardColor.BLACK),
        Card(word="מציאה", color=CardColor.BLUE),
        Card(word="דק", color=CardColor.GRAY),
        Card(word="תולעת", color=CardColor.RED),
        Card(word="מצפון", color=CardColor.RED),
        Card(word="פירמידה", color=CardColor.GRAY),
        Card(word="משובש", color=CardColor.BLUE),
        Card(word="שק", color=CardColor.BLUE),
        Card(word="פנינה", color=CardColor.RED),
        Card(word="דקה", color=CardColor.BLUE),
        Card(word="חג", color=CardColor.BLUE),
        Card(word="קשר", color=CardColor.RED),
        Card(word="קור", color=CardColor.RED),
        Card(word="אויר", color=CardColor.BLUE),
        Card(word="טבליה", color=CardColor.GRAY),
    ]
)
HEBREW_BOARD_4 = Board(
    cards=[
        Card(word="שיר", color=CardColor.BLUE),
        Card(word="הקליד", color=CardColor.BLUE),
        Card(word="חופשה", color=CardColor.RED),
        Card(word="ערב", color=CardColor.RED),
        Card(word="תרמיל", color=CardColor.BLUE),
        Card(word="חוש", color=CardColor.GRAY),
        Card(word="הדר", color=CardColor.RED),
        Card(word="פירמידה", color=CardColor.GRAY),
        Card(word="עגול", color=CardColor.GRAY),
        Card(word="אלתור", color=CardColor.RED),
        Card(word="שנה", color=CardColor.BLUE),
        Card(word="ריבה", color=CardColor.BLUE),
        Card(word="נגן", color=CardColor.BLUE),
        Card(word="בית", color=CardColor.RED),
        Card(word="דמוקרטיה", color=CardColor.GRAY),
        Card(word="ערק", color=CardColor.GRAY),
        Card(word="שחור", color=CardColor.RED),
        Card(word="פרה", color=CardColor.RED),
        Card(word="נס", color=CardColor.BLACK),
        Card(word="בית-ספר", color=CardColor.BLUE),
        Card(word="מצבה", color=CardColor.BLUE),
        Card(word="אגרטל", color=CardColor.GRAY),
        Card(word="מקום", color=CardColor.RED),
        Card(word="תמונה", color=CardColor.GRAY),
        Card(word="מבט", color=CardColor.RED),
    ]
)
HEBREW_BOARD_5 = Board(
    cards=[
        Card(word="שעה", color=CardColor.BLACK),
        Card(word="נסיון", color=CardColor.BLUE),
        Card(word="אחראי", color=CardColor.BLUE),
        Card(word="רכש", color=CardColor.RED),
        Card(word="גרם", color=CardColor.BLUE),
        Card(word="הלכה", color=CardColor.RED),
        Card(word="מונה", color=CardColor.RED),
        Card(word="חור", color=CardColor.GRAY),
        Card(word="בן-גוריון", color=CardColor.GRAY),
        Card(word="ריקוד", color=CardColor.RED),
        Card(word="פריז", color=CardColor.GRAY),
        Card(word="אקדח", color=CardColor.RED),
        Card(word="קניון", color=CardColor.RED),
        Card(word="דני", color=CardColor.GRAY),
        Card(word="ענק", color=CardColor.BLUE),
        Card(word="נפל", color=CardColor.GRAY),
        Card(word="ענן", color=CardColor.BLUE),
        Card(word="די", color=CardColor.GRAY),
        Card(word="רעל", color=CardColor.RED),
        Card(word="מזרק", color=CardColor.BLUE),
        Card(word="אחוז", color=CardColor.GRAY),
        Card(word="ניצחון", color=CardColor.BLUE),
        Card(word="עצם", color=CardColor.RED),
        Card(word="לוחם", color=CardColor.RED),
        Card(word="קהל", color=CardColor.BLUE),
    ]
)
HEBREW_BOARD_6 = Board(
    cards=[
        Card(word="חיים", color=CardColor.GRAY),
        Card(word="ערך", color=CardColor.BLACK),
        Card(word="מסוק", color=CardColor.BLUE),
        Card(word="שבוע", color=CardColor.GRAY),
        Card(word="רובוט", color=CardColor.RED),
        Card(word="פוטר", color=CardColor.GRAY),
        Card(word="אסור", color=CardColor.BLUE),
        Card(word="דינוזאור", color=CardColor.BLUE),
        Card(word="מחשב", color=CardColor.RED),
        Card(word="מעמד", color=CardColor.GRAY),
        Card(word="בעל", color=CardColor.RED),
        Card(word="פנים", color=CardColor.RED),
        Card(word="פרק", color=CardColor.RED),
        Card(word="גפילטע", color=CardColor.BLUE),
        Card(word="שונה", color=CardColor.RED),
        Card(word="שכר", color=CardColor.RED),
        Card(word="קפיץ", color=CardColor.BLUE),
        Card(word="תרסיס", color=CardColor.GRAY),
        Card(word="דגל", color=CardColor.GRAY),
        Card(word="חופשה", color=CardColor.BLUE),
        Card(word="מועדון", color=CardColor.RED),
        Card(word="ציון", color=CardColor.BLUE),
        Card(word="שק", color=CardColor.GRAY),
        Card(word="אקורדיון", color=CardColor.RED),
        Card(word="ילד", color=CardColor.BLUE),
    ]
)
HEBREW_BOARD_7 = Board(
    cards=[
        Card(word="משוב", color=CardColor.RED),
        Card(word="תמנון", color=CardColor.RED),
        Card(word="לקח", color=CardColor.BLUE),
        Card(word="גיס", color=CardColor.BLUE),
        Card(word="עולם", color=CardColor.GRAY),
        Card(word="יצירה", color=CardColor.GRAY),
        Card(word="חציל", color=CardColor.GRAY),
        Card(word="חול", color=CardColor.RED),
        Card(word="קניון", color=CardColor.RED),
        Card(word="פתק", color=CardColor.BLACK),
        Card(word="אלבום", color=CardColor.BLUE),
        Card(word="קיץ", color=CardColor.GRAY),
        Card(word="בירה", color=CardColor.BLUE),
        Card(word="ערק", color=CardColor.RED),
        Card(word="מתח", color=CardColor.GRAY),
        Card(word="בלורית", color=CardColor.GRAY),
        Card(word="טורניר", color=CardColor.BLUE),
        Card(word="מתג", color=CardColor.BLUE),
        Card(word="מפרט", color=CardColor.BLUE),
        Card(word="מזגן", color=CardColor.BLUE),
        Card(word="זריקה", color=CardColor.BLUE),
        Card(word="פאה", color=CardColor.RED),
        Card(word="מפגש", color=CardColor.RED),
        Card(word="כלי", color=CardColor.GRAY),
        Card(word="חיל", color=CardColor.RED),
    ]
)

HEBREW_BOARD_8 = Board(
    cards=[
        Card(word="לילה", color=CardColor.GRAY),
        Card(word="דרך", color=CardColor.BLUE),
        Card(word="שממה", color=CardColor.GRAY),
        Card(word="כנס", color=CardColor.RED),
        Card(word="שיח", color=CardColor.BLUE),
        Card(word="לימון", color=CardColor.RED),
        Card(word="נשמה", color=CardColor.BLUE),
        Card(word="פאה", color=CardColor.GRAY),
        Card(word="כלא", color=CardColor.RED),
        Card(word="טורניר", color=CardColor.BLUE),
        Card(word="שיט", color=CardColor.BLACK),
        Card(word="מת", color=CardColor.BLUE),
        Card(word="מתח", color=CardColor.RED),
        Card(word="אף", color=CardColor.RED),
        Card(word="אור", color=CardColor.RED),
        Card(word="סבא", color=CardColor.GRAY),
        Card(word="רעב", color=CardColor.GRAY),
        Card(word="נמל", color=CardColor.BLUE),
        Card(word="קצב", color=CardColor.BLUE),
        Card(word="מטריה", color=CardColor.BLUE),
        Card(word="דבר", color=CardColor.GRAY),
        Card(word="שר", color=CardColor.BLUE),
        Card(word="מצקת", color=CardColor.RED),
        Card(word="עם", color=CardColor.GRAY),
        Card(word="אפריקה", color=CardColor.RED),
    ]
)
